name: Deploy to GitHub Pages

on:
  push:
    branches: [main]          # adjust if you use 'master'
  workflow_dispatch:

# minimum token scopes for a Pages deployment
permissions:
  contents: read              # checkout + build
  pages:    write             # publish
  id-token: write             # verify provenance

concurrency:
  group: "pages"
  cancel-in-progress: true    # abort older builds if you push fast

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4      # Node 20 LTS
        with:
          node-version: 20
          cache: npm

      - run: npm ci                      # or 'pnpm install'

      - run: npm run build               # Next.js ➜ ./out  (needs output:'export')

      # NEW: upload with
